import type { Equipment, Muscle } from './types'

// Ejercicios precargados. El id es el de free-exercise-db (dominio público), que también da las
// imágenes de la animación: https://github.com/yuhonas/free-exercise-db
type Seed = [id: string, nameEs: string, nameEn: string, muscle: Muscle, equipment: Equipment]

export const SEED_EXERCISES: Seed[] = [
  // Pecho
  ['Barbell_Bench_Press_-_Medium_Grip', 'Press de banca con barra', 'Barbell Bench Press', 'chest', 'barbell'],
  ['Barbell_Incline_Bench_Press_-_Medium_Grip', 'Press inclinado con barra', 'Incline Barbell Bench Press', 'chest', 'barbell'],
  ['Decline_Barbell_Bench_Press', 'Press declinado con barra', 'Decline Barbell Bench Press', 'chest', 'barbell'],
  ['Dumbbell_Bench_Press', 'Press de banca con mancuernas', 'Dumbbell Bench Press', 'chest', 'dumbbell'],
  ['Incline_Dumbbell_Press', 'Press inclinado con mancuernas', 'Incline Dumbbell Press', 'chest', 'dumbbell'],
  ['Machine_Bench_Press', 'Press de pecho en máquina', 'Machine Chest Press', 'chest', 'machine'],
  ['Dumbbell_Flyes', 'Aperturas con mancuernas', 'Dumbbell Flyes', 'chest', 'dumbbell'],
  ['Incline_Dumbbell_Flyes', 'Aperturas inclinadas con mancuernas', 'Incline Dumbbell Flyes', 'chest', 'dumbbell'],
  ['Butterfly', 'Pec deck (contractor)', 'Pec Deck', 'chest', 'machine'],
  ['Cable_Crossover', 'Cruce de poleas', 'Cable Crossover', 'chest', 'cable'],
  ['Pushups', 'Flexiones', 'Push-Ups', 'chest', 'bodyweight'],
  ['Dips_-_Chest_Version', 'Fondos para pecho', 'Chest Dips', 'chest', 'bodyweight'],
  // Espalda
  ['Barbell_Deadlift', 'Peso muerto', 'Deadlift', 'back', 'barbell'],
  ['Pullups', 'Dominadas', 'Pull-Ups', 'back', 'bodyweight'],
  ['Chin-Up', 'Dominadas supinas', 'Chin-Ups', 'back', 'bodyweight'],
  ['Wide-Grip_Lat_Pulldown', 'Jalón al pecho agarre ancho', 'Wide-Grip Lat Pulldown', 'back', 'cable'],
  ['Close-Grip_Front_Lat_Pulldown', 'Jalón al pecho agarre cerrado', 'Close-Grip Lat Pulldown', 'back', 'cable'],
  ['Bent_Over_Barbell_Row', 'Remo con barra', 'Barbell Row', 'back', 'barbell'],
  ['One-Arm_Dumbbell_Row', 'Remo con mancuerna a una mano', 'One-Arm Dumbbell Row', 'back', 'dumbbell'],
  ['Seated_Cable_Rows', 'Remo sentado en polea', 'Seated Cable Row', 'back', 'cable'],
  ['T-Bar_Row_with_Handle', 'Remo en T', 'T-Bar Row', 'back', 'barbell'],
  ['Leverage_Iso_Row', 'Remo en máquina', 'Machine Row', 'back', 'machine'],
  ['Straight-Arm_Pulldown', 'Pullover en polea', 'Straight-Arm Pulldown', 'back', 'cable'],
  ['Hyperextensions_Back_Extensions', 'Hiperextensiones', 'Back Extensions', 'back', 'other'],
  // Hombros
  ['Standing_Military_Press', 'Press militar con barra', 'Overhead Press', 'shoulders', 'barbell'],
  ['Dumbbell_Shoulder_Press', 'Press de hombros con mancuernas', 'Dumbbell Shoulder Press', 'shoulders', 'dumbbell'],
  ['Arnold_Dumbbell_Press', 'Press Arnold', 'Arnold Press', 'shoulders', 'dumbbell'],
  ['Machine_Shoulder_Military_Press', 'Press de hombros en máquina', 'Machine Shoulder Press', 'shoulders', 'machine'],
  ['Side_Lateral_Raise', 'Elevaciones laterales', 'Lateral Raise', 'shoulders', 'dumbbell'],
  ['Cable_Seated_Lateral_Raise', 'Elevaciones laterales en polea', 'Cable Lateral Raise', 'shoulders', 'cable'],
  ['Front_Dumbbell_Raise', 'Elevaciones frontales', 'Front Raise', 'shoulders', 'dumbbell'],
  ['Reverse_Flyes', 'Pájaros con mancuernas', 'Reverse Flyes', 'shoulders', 'dumbbell'],
  ['Reverse_Machine_Flyes', 'Deltoides posterior en máquina', 'Reverse Pec Deck', 'shoulders', 'machine'],
  ['Face_Pull', 'Face pull', 'Face Pull', 'shoulders', 'cable'],
  ['Barbell_Shrug', 'Encogimientos con barra', 'Barbell Shrug', 'shoulders', 'barbell'],
  ['Dumbbell_Shrug', 'Encogimientos con mancuernas', 'Dumbbell Shrug', 'shoulders', 'dumbbell'],
  // Bíceps
  ['Barbell_Curl', 'Curl con barra', 'Barbell Curl', 'biceps', 'barbell'],
  ['EZ-Bar_Curl', 'Curl con barra Z', 'EZ-Bar Curl', 'biceps', 'barbell'],
  ['Dumbbell_Bicep_Curl', 'Curl con mancuernas', 'Dumbbell Curl', 'biceps', 'dumbbell'],
  ['Hammer_Curls', 'Curl martillo', 'Hammer Curl', 'biceps', 'dumbbell'],
  ['Incline_Dumbbell_Curl', 'Curl inclinado con mancuernas', 'Incline Dumbbell Curl', 'biceps', 'dumbbell'],
  ['Preacher_Curl', 'Curl predicador', 'Preacher Curl', 'biceps', 'barbell'],
  ['Concentration_Curls', 'Curl concentrado', 'Concentration Curl', 'biceps', 'dumbbell'],
  // Tríceps
  ['Triceps_Pushdown', 'Extensión de tríceps en polea', 'Triceps Pushdown', 'triceps', 'cable'],
  ['Triceps_Pushdown_-_Rope_Attachment', 'Extensión de tríceps con cuerda', 'Rope Pushdown', 'triceps', 'cable'],
  ['Triceps_Overhead_Extension_with_Rope', 'Extensión de tríceps sobre la cabeza', 'Overhead Triceps Extension', 'triceps', 'cable'],
  ['EZ-Bar_Skullcrusher', 'Press francés', 'Skull Crusher', 'triceps', 'barbell'],
  ['Close-Grip_Barbell_Bench_Press', 'Press de banca agarre cerrado', 'Close-Grip Bench Press', 'triceps', 'barbell'],
  ['Dips_-_Triceps_Version', 'Fondos para tríceps', 'Triceps Dips', 'triceps', 'bodyweight'],
  ['Tricep_Dumbbell_Kickback', 'Patada de tríceps', 'Triceps Kickback', 'triceps', 'dumbbell'],
  // Piernas
  ['Barbell_Squat', 'Sentadilla con barra', 'Barbell Squat', 'legs', 'barbell'],
  ['Front_Barbell_Squat', 'Sentadilla frontal', 'Front Squat', 'legs', 'barbell'],
  ['Smith_Machine_Squat', 'Sentadilla en Smith', 'Smith Machine Squat', 'legs', 'machine'],
  ['Goblet_Squat', 'Sentadilla goblet', 'Goblet Squat', 'legs', 'other'],
  ['Hack_Squat', 'Sentadilla hack', 'Hack Squat', 'legs', 'machine'],
  ['Leg_Press', 'Prensa de piernas', 'Leg Press', 'legs', 'machine'],
  ['Split_Squat_with_Dumbbells', 'Sentadilla búlgara', 'Bulgarian Split Squat', 'legs', 'dumbbell'],
  ['Dumbbell_Lunges', 'Zancadas con mancuernas', 'Dumbbell Lunges', 'legs', 'dumbbell'],
  ['Barbell_Lunge', 'Zancadas con barra', 'Barbell Lunge', 'legs', 'barbell'],
  ['Leg_Extensions', 'Extensión de cuádriceps', 'Leg Extension', 'legs', 'machine'],
  ['Lying_Leg_Curls', 'Curl femoral acostado', 'Lying Leg Curl', 'legs', 'machine'],
  ['Seated_Leg_Curl', 'Curl femoral sentado', 'Seated Leg Curl', 'legs', 'machine'],
  ['Romanian_Deadlift', 'Peso muerto rumano', 'Romanian Deadlift', 'legs', 'barbell'],
  ['Stiff-Legged_Dumbbell_Deadlift', 'Peso muerto con mancuernas', 'Dumbbell Stiff-Leg Deadlift', 'legs', 'dumbbell'],
  ['Sumo_Deadlift', 'Peso muerto sumo', 'Sumo Deadlift', 'legs', 'barbell'],
  ['Standing_Calf_Raises', 'Elevación de talones de pie', 'Standing Calf Raise', 'legs', 'machine'],
  ['Seated_Calf_Raise', 'Elevación de talones sentado', 'Seated Calf Raise', 'legs', 'machine'],
  ['Thigh_Adductor', 'Aductores en máquina', 'Hip Adduction Machine', 'legs', 'machine'],
  // Glúteos
  ['Barbell_Hip_Thrust', 'Hip thrust con barra', 'Barbell Hip Thrust', 'glutes', 'barbell'],
  ['Barbell_Glute_Bridge', 'Puente de glúteos con barra', 'Barbell Glute Bridge', 'glutes', 'barbell'],
  ['Thigh_Abductor', 'Abductores en máquina', 'Hip Abduction Machine', 'glutes', 'machine'],
  ['Glute_Kickback', 'Patada de glúteo', 'Glute Kickback', 'glutes', 'bodyweight'],
  ['Pull_Through', 'Pull-through en polea', 'Cable Pull-Through', 'glutes', 'cable'],
  // Core
  ['Crunches', 'Crunch abdominal', 'Crunches', 'core', 'bodyweight'],
  ['Cable_Crunch', 'Crunch en polea', 'Cable Crunch', 'core', 'cable'],
  ['Hanging_Leg_Raise', 'Elevación de piernas colgado', 'Hanging Leg Raise', 'core', 'bodyweight'],
  ['Russian_Twist', 'Giros rusos', 'Russian Twist', 'core', 'bodyweight'],
  ['Ab_Roller', 'Rueda abdominal', 'Ab Wheel Rollout', 'core', 'other'],
]
